### ISSUE TITLE
Sepsis, Change MiSeq tracker column name from "Analytical Platform" to "MiSeq"

### ISSUE THREAD

**Issue by sthysel** [muccg/bpa-metadata#49]
There's a minor change to be made to the MiSeq tracker. I put in the wrong value in the Google Doc and did not notice. 

Have attached the screen shot here.  
![screenshot_miseq tracker](https://cloud.githubusercontent.com/assets/148329/18370566/b2e190e4-7660-11e6-9d65-e73b670e68f3.png)

**Comment by sthysel** [comment]
Because the column name changes the source doc's col name should also change, does this apply to some of the other track tables as well ?

**Comment by mabelbpa** [comment]
Sorry for the confusion.

Under "Track MiSeq", please change the value from PacBio to Miseq. The column heading remains as "Analytical Platform". Cheers

**Comment by sthysel** [comment]
Right, so you can easily fix that by updating the spreadsheet and just re-uploading it again. Or alternatively use the other admin facilities to edit the particular entry:

https://downloads.bioplatforms.com/admin/sepsis/miseqtrack/27/

If they are all wrong, just fix the source doc and re-upload.

**Comment by mabelbpa** [comment]
I tried to re-upload and there was an error.

I deleted all the items in Track Miseq and tried to reupload but there was still an error. 

Errors

    Line number: 1 - duplicate key value violates unique constraint "common_bpauniqueid_pkey" DETAIL: Key (bpa_id)=(102.100.100.25705) already exists. 

I think the problem is MiSeq and PacBio data share the same ID. On a separate but related issue, there are now discussions to use the same BPA ID for Track SWATH-MS and Track LC-MS. From your perspective, should we have separate IDs? I don't want to have issues with uploading the file onto the portal.

**Comment by mabelbpa** [comment]
If it is too hard to upload because of duplicate ID, could you restore the items I deleted on Track Miseq and I will change them individually.

**Comment by sthysel** [comment]
Verified issue exists on prod, can't replicate in master or next_release though.

**Comment by mabelbpa** [comment]
Meaning?

**Comment by sthysel** [comment]
OK, stack rebuild in dev with new DB and can replicate in dev now. Must have missed a migration.
